#!/usr/bin/env ruby
#
puts Time.now.to_s

puts "============"

puts "rm -rf docs/"
`rm -rf docs/`

puts "bundle exec rake guides:generate"
`bundle exec rake guides:generate`

puts "============"


Dir["docs/*.html"].each do |path|
  puts File.expand_path(File.dirname(__FILE__)) + "/" + path
end

puts "============"

# rake guides:generate（rake --task）
# 作用是将md生成为html，但是生成目录固定是output目录，不能指定目录
# 矛盾的是github指定目录也是固定的，docs目录
# 所以，我在此加了一个重命名操作
puts "mv output docs"
`mv output docs`
